function pkmPerYearPerCountry = ReturnpkmPerYearPerCountry(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  PKMPERYEARPERCOUNTRY = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  PKMPERYEARPERCOUNTRY = IMPORTFILE(FILE, SHEET) reads from the
%  specified worksheet.
%
%  PKMPERYEARPERCOUNTRY = IMPORTFILE(FILE, SHEET, DATALINES) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  pkmPerYearPerCountry = importfile("/Users/jsgerber/sandbox/jsg216_MappingIndividualSolutions/ElectricVehicles/pkmPerYearPerCountry.xlsx", "Sheet1", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 10-Mar-2025 16:41:48

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 18);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Author", "YearPublished", "Title", "DOIOrReferenceLink", "SourceType", "CheckIfPeerreviewed", "StudyType", "StudyQuality", "OfStudiesIfMetaanalysisOrReview", "Region", "Subregion", "SpecificCountryOrRegion", "CountryCode", "DataYearvsYearOfPublication", "Population2020", "NumberOfRegisteredVehicles", "TotalDistanceTraveledByPrivateCarIn2019pkmyear", "DistanceTraveledByCarpkmvehicleyear"];
opts.VariableTypes = ["categorical", "double", "categorical", "categorical", "categorical", "string", "categorical", "categorical", "string", "categorical", "categorical", "string", "string", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["CheckIfPeerreviewed", "OfStudiesIfMetaanalysisOrReview", "SpecificCountryOrRegion", "CountryCode"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Author", "Title", "DOIOrReferenceLink", "SourceType", "CheckIfPeerreviewed", "StudyType", "StudyQuality", "OfStudiesIfMetaanalysisOrReview", "Region", "Subregion", "SpecificCountryOrRegion", "CountryCode"], "EmptyFieldRule", "auto");

% Import the data
pkmPerYearPerCountry = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    pkmPerYearPerCountry = [pkmPerYearPerCountry; tb]; %#ok<AGROW>
end

end