function DradwdownNGOGNR2022S9 = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  DRADWDOWNNGOGNR2022S9 = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  DRADWDOWNNGOGNR2022S9 = IMPORTFILE(FILE, SHEET) reads from the
%  specified worksheet.
%
%  DRADWDOWNNGOGNR2022S9 = IMPORTFILE(FILE, SHEET, DATALINES) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  DradwdownNGOGNR2022S9 = importGCCA("/Users/jsgerber/sandbox/jsg216_MappingIndividualSolutions/Sol42_ImproveCementProduction/Dradwdown_NGO_GNR_2022.xlsx", "Canada", [12, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Feb-2025 14:21:48 with subsequent
% modifications by j gerber

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [12, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 9);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Region", "Year", "Value", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9"];
opts.VariableTypes = ["categorical", "double", "double", "double", "string", "string", "string", "string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["VarName5", "VarName6", "VarName7", "VarName8", "VarName9"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Region", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9"], "EmptyFieldRule", "auto");

% Import the data
DradwdownNGOGNR2022S9 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    DradwdownNGOGNR2022S9 = [DradwdownNGOGNR2022S9; tb]; %#ok<AGROW>
end

end