function FBSToPoore = FBStoPoore(workbookFile, sheetName, dataLines)
%IMPORTFILE3 Import data from a spreadsheet
%  FBSTOPOORE = IMPORTFILE3(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  FBSTOPOORE = IMPORTFILE3(FILE, SHEET) reads from the specified
%  worksheet.
%
%  FBSTOPOORE = IMPORTFILE3(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  FBSToPoore = FBStoPoore("/Users/jsgerber/sandbox/jsg216_MappingIndividualSolutions/Sol24_ReduceFoodLossAndWaste/flwfromgattotables/FBSToPoore.xlsx", "Sheet1", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Jan-2025 13:25:00

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["FBSItem", "FBSItem_Code", "UniqueCode"];
opts.VariableTypes = ["string", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "FBSItem", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "FBSItem", "EmptyFieldRule", "auto");

% Import the data
FBSToPoore = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    FBSToPoore = [FBSToPoore; tb]; %#ok<AGROW>
end

end