function TableS13Full = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  TABLES13FULL = IMPORTFILE1(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  TABLES13FULL = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  TableS13Full = importfile1("/Users/jsgerber/sandbox/jsg216_MappingIndividualSolutions/Sol24_ReduceFoodLossAndWaste/flwfromgattotables/TableS13Full.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-Jan-2025 18:41:05

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["FBSCommodity", "FLWCommodityGroup", "GTAPSector"];
opts.VariableTypes = ["string", "categorical", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "FBSCommodity", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["FBSCommodity", "FLWCommodityGroup", "GTAPSector"], "EmptyFieldRule", "auto");

% Import the data
TableS13Full = readtable(filename, opts);

end