function GTAPFLWGatto2024 = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  GTAPFLWGATTO2024 = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  GTAPFLWGATTO2024 = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  GTAPFLWGATTO2024 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  GTAPFLWGatto2024 = importfile("/Users/jsgerber/sandbox/jsg216_MappingIndividualSolutions/Sol24_ReduceFoodLossAndWaste/flwfromgattotables/rawtablesforextraction/GTAP-FLW_Gatto-2024.xlsx", "Table S1 – Western Europe", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-Jan-2025 09:33:54
%
% Modified by JSG to force strings.

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 6);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["CommodityGTAP", "AgriculturalProduction", "PostharvestHandlingStorage", "Manufacturing", "DistributionRetail", "Consumption"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["CommodityGTAP", "PostharvestHandlingStorage"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["CommodityGTAP", "PostharvestHandlingStorage"], "EmptyFieldRule", "auto");

% Import the data
GTAPFLWGatto2024 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    GTAPFLWGatto2024 = [GTAPFLWGatto2024; tb]; %#ok<AGROW>
end

end