function SimplefoodwasteGHGcomparisonsPlus = ImportPoorePlus(filename, dataLines)
%IMPORTFILE3 Import data from a text file
%  SIMPLEFOODWASTEGHGCOMPARISONSPLUS = IMPORTFILE3(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  SIMPLEFOODWASTEGHGCOMPARISONSPLUS = IMPORTFILE3(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  SimplefoodwasteGHGcomparisonsPlus = ImportPoorePlus("/Users/jsgerber/sandbox/jsg216_MappingIndividualSolutions/Sol24_ReduceFoodLossAndWaste/flwfromgattotables/Simple-food-waste-GHG-comparisonsPlus.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Jan-2025 13:30:58

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["ProductPooreNemecekClassification", "FBSIIICode", "FBSIVCode", "FBSName", "UniqueCode", "FoodAndWaste1000t", "LUC", "Feed", "Farm", "Processing", "Transport", "Packging", "SUMkg"];
opts.VariableTypes = ["string", "double", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["ProductPooreNemecekClassification", "FBSName"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["ProductPooreNemecekClassification", "FBSName"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "FoodAndWaste1000t", "TrimNonNumeric", true);
opts = setvaropts(opts, "FoodAndWaste1000t", "ThousandsSeparator", ",");

% Import the data
SimplefoodwasteGHGcomparisonsPlus = readtable(filename, opts);

end