function groups = groupFBSItems(itemList)
% groupFBSItems
%
% INPUT
%   itemList : cell array of strings (FAOSTAT item names)
%
% OUTPUT
%   groups : struct array with fields
%       - GroupName : name of FBS aggregate
%       - Items     : cell array of items from itemList in that group
%
% Example:
%   items = {'Bovine Meat','Pigmeat','Wheat and Meslin','Cassava and Products'};
%   groups = groupFBSItems(items);



% This function was written by ChatGPT with the following prompt:
% Could you please write me a matlab function that takes as an argument a
% list of Items (a cell array of strings) and returns a vector of
% structures, where each structure corresponds to a group item, and has one
% field which is the name of the group item, and one field which contains
% all of the items which are in the argument list.    
%
% Preceding this I had asked Chat GPT to construct the list based on Food
% Balance Sheets.

    % ---- normalize input ----
    itemList = itemList(:);  % force column
    itemList = string(itemList);

    % ---- define FBS hierarchy ----
    H = struct( ...
        'GroupName', { ...
            'Cereals', ...
            'Starchy Roots', ...
            'Pulses', ...
            'Vegetables', ...
            'Fruits - Excluding Wine', ...
            'Oils and Fats', ...
            'Sugar & Sweeteners', ...
            'Meat', ...
            'Milk - Excluding Butter', ...
            'Fish and Seafood' ...
        }, ...
        'Items', { ...
            ["Wheat and Meslin","Rice (Milled Equivalent)","Barley","Maize","Rye","Oats","Millet","Sorghum","Cereals, Other"], ...
            ["Potatoes","Cassava and Products","Sweet Potatoes","Yams","Roots and Tubers, Other"], ...
            ["Beans","Peas","Chickpeas","Lentils","Pulses, Other"], ...
            ["Tomatoes","Onions","Vegetables, Other"], ...
            ["Oranges","Mandarins","Lemons and Limes","Grapefruit","Bananas","Apples","Pineapples","Fruits, Other"], ...
            ["Soybean Oil","Palm Oil","Sunflower Oil","Rapeseed Oil","Groundnut Oil","Coconut Oil","Olive Oil","Oils, Other"], ...
            ["Sugar (Raw Equivalent)","Honey","Sweeteners, Other"], ...
            ["Bovine Meat","Mutton & Goat Meat","Pigmeat","Poultry Meat","Meat, Other","Offals, Edible"], ...
            ["Milk, Whole","Milk, Skimmed"], ...
            ["Freshwater Fish","Demersal Fish","Pelagic Fish","Marine Fish, Other","Crustaceans","Molluscs","Aquatic Animals, Others"] ...
        } ...
    );

    % ---- build output ----
    groups = struct('GroupName', {}, 'Items', {});

    for i = 1:numel(H)
        % find overlap between input items and this group
        inGroup = intersect(itemList, H(i).Items, 'stable');

        if ~isempty(inGroup)
            groups(end+1).GroupName = H(i).GroupName; %#ok<AGROW>
            groups(end).Items     = cellstr(inGroup);
        end
    end
end